---
- name: change user password before expiry 
  hosts: all
  become: yes
  vars:
      user_list: ["ansusr"]
  tasks:
  - name: capture the password expiration information in term of number of days 
    shell: >
        expr $(date -d "$(chage -l {{ item }} | grep 'Password expires' | cut -d: -f2)" +%s) / 86400 - $(date +%s) / 86400
    loop: "{{ user_list }}"
    register: days_until_expiration
  - name: display the password expiration information in term of number of days for each user
    debug:
         msg: "User: {{ item.item }}, Days until password expiration: {{ item.stdout }}"
    loop: "{{ days_until_expiration.results }}"
  - name: generate the password
    shell: openssl rand -base64 16
    register: generated_password
  - name: display the generated password
    debug:
         msg: "{{ generated_password }}" 
  - name: hash the generated password
    set_fact: 
         hashed_password: "{{ generated_password.stdout | password_hash('sha512') }}"
    register: encrypted_password
  - name: display the hashed password 
    debug: 
         msg: "{{ encrypted_password }}"  
  - name: change password for users expiring within 7 days 
    user:
         name: "{{ item.item }}"      
         password: "{{ hashed_password }}"
    loop: "{{ days_until_expiration.results }}"
    when:  (item.stdout | int) < 7
